# Generated by Django 5.1.7 on 2025-03-13 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waters',
            options={'ordering': ['-created_at'], 'verbose_name': 'Waters'},
        ),
    ]
